### ISSUE TITLE
Option to use the left-most part of the selection when one is active?

### ISSUE THREAD

**Issue by ghost** [stevenhauser/atom-simple-align#1]
Hello

I've recently started using this package and it was exactly what I'm looking for, thanks! However, I've been wondering a bit about how selections are intended to be handled? For example (where `|` denotes the bounds of the selection):

```
var a |=| 1;
var ab |=| 2;
var abc |=| 3;
```

What should happen in this case? I've noticed that currently alignment will happen wherever the cursor ended, so if I had my three cursors to the left of the equal signs, then selected it using `shift+right`, alignment would happen as if the cursor was after the equal signs, i.e.:

```
var a =| 1;
var ab =| 2;
var abc =| 3;
```

If, however, my cursor was after the equal signs and I moved left using `shift-left`, alignment will happen to the left of the equal signs.

Would it perhaps be a good idea to add a configuration option to always use the left-most (or right-most) part of the selection instead? This adds a certain degree of predictability and is especially useful if you often use the 'select next occurrence' from Atom's find and replace to quickly select lines that look alike and must be aligned together.

Thanks in advance

**Comment by stevenhauser** [comment]
Hey, I'm sorry that I didn't see this. I didn't have notifications on for this repo. 

The intention of this alignment package is to not really deal with _selections_ but rather cursors. In your examples—if I'm understanding them correctly—you're trying to align a selected `=` sign, when all that this package attempts to do is align the cursors and completely ignores the selection. So what I would recommend is to not have selections when aligning, but rather just "flat" cursors. So if you select all the `=` signs, then you'd just left-arrow to deselect them and be left with multiple cursors that would be aligned on. And if you for some reason wanted to align the numbers instead, you'd arrow key right to have multiple cursors to the right of the `=` (and maybe move one more space over) and then align on those.

I think that your concept of using the leftmost part of a selection would be fine in most cases, but I could also see some people expecting it to happen on the right. And while configuration could solve this, I think that it complicates the issue, whereas just dealing with cursors as explained above keeps things nice and simple.

**Comment by ghost** [comment]
Yes, that is correct. I am indeed aware of the fact that moving the cursor solves the issue, my proposition was a bit to remove the need for an additional keystroke as well as because I found myself accidentally trying to align the items without removing the selection first, which then resulted in somewhat unpredictable behavior as it depends on how the selection was made (from left to right or right to left).

Also, no worries about the delayed response. In fact I had the exact same problem when I opened a repository (I expected notifications for my own repositories to be automatically enabled).

**Comment by stevenhauser** [comment]
Gotcha, that makes sense. However, I think for the scope of this project I want to stick only with cursors (and not selections) in keeping with the `simple` part of it. But of course feel free to fork this project and add the support you're looking for. I do know that there are several other alignment plugins that do a lot more than this one—this one's goal is to be as simple as possible. And thanks for understanding about the notifications.

**Comment by ghost** [comment]
Ok, no problem. Thanks for your response. I'll close this ticket for your convenience ;-).
