### ISSUE TITLE
Multi row selection example

### ISSUE THREAD

**Issue by csholmq** [stevenhauser/atom-simple-align#2]
Missing instructions on how to reproduce your multi row selection example in your GIF. Is that from another package?

**Comment by andre-luiz-dos-santos** [comment]
Natively, there's _Control + D_, _Alt + Shift + (Down/Up)_, etc.

**Comment by stevenhauser** [comment]
Sorry, didn't see this because I had notifications off for this repo on accident. @csholmq did @andre-luiz-dos-santos answer your question? That's the way I do it. And thanks @andre-luiz-dos-santos for answering!

**Comment by csholmq** [comment]
At first I didn't think it did. But only because Alt + Shift + (Up/Down) didn't work for me (OS X). Then I noticed that (Ctrl/Cmd) + D worked like a charm if you just pressed it repeatedly. It keeps on selecting all instances of the corresponding word (or character) for every execution.

TBH I wouldn't have caught my eye on this if that GIF hadn't been in the readme. (Ctrl/Cmd) + D is really what makes this work. But maybe that's just me.

Thanks @andre-luiz-dos-santos  and @stevenhauser !
